CREATE TYPE "auth_method_enum" AS ENUM ('traditional', 'google', 'facebook', 'x');

CREATE TABLE "Users" (
    "id" SERIAL PRIMARY KEY,
    "firstName" VARCHAR(255) NOT NULL,
    "lastName" VARCHAR(255) NOT NULL,
    "profilePicture" TEXT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255),
    "authMethod" "auth_method_enum" NOT NULL DEFAULT 'traditional',
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "UserTasteProfiles" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    "sweetness" FLOAT NOT NULL DEFAULT 0.0,
    "saltiness" FLOAT NOT NULL DEFAULT 0.0,
    "sourness" FLOAT NOT NULL DEFAULT 0.0,
    "bitterness" FLOAT NOT NULL DEFAULT 0.0,
    "savoriness" FLOAT NOT NULL DEFAULT 0.0,
    "spiciness" FLOAT NOT NULL DEFAULT 0.0,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Users" ADD COLUMN "tasteProfileId" INTEGER NULL REFERENCES "UserTasteProfiles" ("id") ON DELETE SET NULL;

CREATE TABLE "Bookmarks" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    "recipeIds" INTEGER[] NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE
    "Recipes" (
        "id" SERIAL PRIMARY KEY,
        "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
        "title" VARCHAR(255) NOT NULL,
        "shortDescription" TEXT NULL,
        "instructions" TEXT NOT NULL,
        "headlinerImage" TEXT NULL,
        "datePublished" TIMESTAMP WITH TIME ZONE NOT NULL,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE "RecipeTasteProfiles" (
    "id" SERIAL PRIMARY KEY,
    "recipeId" INTEGER NOT NULL REFERENCES "Recipes" ("id") ON DELETE CASCADE,
    "sweetness" FLOAT NOT NULL DEFAULT 0.0,
    "saltiness" FLOAT NOT NULL DEFAULT 0.0,
    "sourness" FLOAT NOT NULL DEFAULT 0.0,
    "bitterness" FLOAT NOT NULL DEFAULT 0.0,
    "savoriness" FLOAT NOT NULL DEFAULT 0.0,
    "spiciness" FLOAT NOT NULL DEFAULT 0.0,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Recipes" ADD COLUMN "tasteProfileId" INTEGER NULL REFERENCES "RecipeTasteProfiles" ("id") ON DELETE SET NULL;

CREATE TABLE "Ingredients" (
    "id" SERIAL PRIMARY KEY,
    "recipeId" INTEGER NOT NULL REFERENCES "Recipes" ("id") ON DELETE CASCADE,
    "name" VARCHAR(255) NOT NULL,
    "quantity" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Recipes" ADD COLUMN "ingredientsId" INTEGER NULL REFERENCES "Ingredients" ("id") ON DELETE SET NULL;

CREATE TABLE "Comments" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    "recipeId" INTEGER NOT NULL REFERENCES "Recipes" ("id") ON DELETE CASCADE,
    "comment" TEXT NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Recipes" ADD COLUMN "commentId" INTEGER NULL REFERENCES "Comments" ("id") ON DELETE SET NULL;

-- more efficient to store the count in the recipe table rather than calculate it every time
ALTER TABLE "Recipes" ADD COLUMN "bookmarkCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Recipes" ADD COLUMN "commentCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Recipes" ADD COLUMN "ratingCount" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE "Tags" (
    "id" SERIAL PRIMARY KEY,
    "recipeId" INTEGER NOT NULL REFERENCES "Recipes" ("id") ON DELETE CASCADE,
    "name" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Ratings" (
    "id" SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
    "recipeId" INTEGER NOT NULL REFERENCES "Recipes" ("id") ON DELETE CASCADE,
    "rating" FLOAT NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);



